---
apiVersion: v1
kind: Service
metadata:
  name: follower
  labels:
    app: follower
spec:
  ports:
  - port: 443
    name: https
  selector:
    app: follower
  type: LoadBalancer
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: follower
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: follower
        name: follower
        role: follower
    spec:
      serviceAccountName: conjur-cluster
      containers:
      - name: conjur-appliance
        image: docker-registry.default.svc:5000/dap/conjur-appliance:11.2.1
        imagePullPolicy: IfNotPresent
        env:
          - name: CONJUR_AUTHENTICATORS
            value: authn-k8s/okd
        ports:
        - containerPort: 443
          name: https
        - containerPort: 636
          name: ldaps
        - containerPort: 5432
          name: pg-main
        - containerPort: 5433
          name: pg-audit
