---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-restapi-sidecar
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-restapi-sidecar
  labels:
    app: cityapp-restapi-sidecar
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: cityapp-restapi-sidecar
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cityapp-restapi-sidecar
  name: cityapp-restapi-sidecar
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: cityapp-restapi-sidecar
  wildcardPolicy: None
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: cityapp-restapi-sidecar
  name: cityapp-restapi-sidecar
spec:
  replicas: 1
  selector:
    app: cityapp-restapi-sidecar
  template:
    metadata:
      labels:
        app: cityapp-restapi-sidecar
    spec:
      serviceAccountName: cityapp-restapi-sidecar
      containers:
      - image: docker-registry.default.svc:5000/cityapp/cityapp:latest
        name: cityapp
        env:
          - name: DBAddress
            value: "mysql01.cyberarkdemo.com"
          - name: DBPort
            value: "3306"
          - name: DBName
            value: "world"
          - name: DBPassword_CONJUR_VAR
            value: "Vault/Demo/DB-App/mysql01-cityapp/password"
          - name: DBUsername_CONJUR_VAR
            value: "Vault/Demo/DB-App/mysql01-cityapp/username"
          - name: CONJUR_APPLIANCE_URL
            value: "https://follower.dap.svc.cluster.local/api"
          - name: CONJUR_ACCOUNT
            value: cyberark
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: cityapp
                key: ssl-certificate
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
          - name: CONJUR_VERSION
            value: "5"
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
      - image: docker-registry.default.svc:5000/cityapp/conjur-kubernetes-authenticator:latest
        imagePullPolicy: Always
        name: authenticator
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_APPLIANCE_URL
            value: "https://follower.dap.svc.cluster.local/api"
          - name: CONJUR_AUTHN_URL
            value: "https://follower.dap.svc.cluster.local/api/authn-k8s/okd"
          - name: CONJUR_ACCOUNT
            value: cyberark
          - name: CONJUR_AUTHN_LOGIN
            value: "host/conjur/authn-k8s/okd/apps/cityapp/service_account/cityapp-restapi-sidecar"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: cityapp
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
#      imagePullSecrets:
#        - name: dockerpullsecret
