---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-summon-init
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-summon-init
  labels:
    app: cityapp-summon-init
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: cityapp-summon-init
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cityapp-summon-init
  name: cityapp-summon-init
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: cityapp-summon-init
  wildcardPolicy: None
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: cityapp-summon-init
  name: cityapp-summon-init
spec:
  replicas: 1
  selector:
    app: cityapp-summon-init
  template:
    metadata:
      labels:
        app: cityapp-summon-init
    spec:
      serviceAccountName: cityapp-summon-init
      containers:
      - image: docker-registry.default.svc:5000/cityapp/cityapp:latest
        imagePullPolicy: Always
        name: cityapp
        env:
# These will be injected as literal value by summon
#          - name: DBAddress
#            value: "mysql01.cyberarkdemo.com"
#          - name: DBName
#            value: "world"
#          - name: DBPort
#            value: "3306"
          - name: CONJUR_APPLIANCE_URL
            value: "https://follower.dap.svc.cluster.local/api"
          - name: CONJUR_ACCOUNT
            value: "cyberark"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: follower-certificate
                key: ssl-certificate
          - name: CONJUR_AUTHN_TOKEN_FILE
            value: /run/conjur/access-token
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
            readOnly: true
          - mountPath: /etc/summon
            name: summon-config
            readOnly: true
        command: [ "summon", "-f", "/etc/summon/secrets.yaml", "ruby", "/usr/src/cityapp.rb", "-o", "0.0.0.0" ]
      initContainers:  # comment this line to troubleshoot authenticator container
      - image:  docker-registry.default.svc:5000/cityapp/conjur-kubernetes-authenticator:latest
        imagePullPolicy: Always
        name: authenticator
        env:
          - name: CONTAINER_MODE
            value: init
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_APPLIANCE_URL
            value: "https://follower.dap.svc.cluster.local/api"
          - name: CONJUR_AUTHN_URL
            value: "https://follower.dap.svc.cluster.local/api/authn-k8s/okd"
          - name: CONJUR_ACCOUNT
            value: "cyberark"
          - name: CONJUR_AUTHN_LOGIN
            value: "host/conjur/authn-k8s/okd/apps/cityapp/service_account/cityapp-summon-init"
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: follower-certificate
                key: ssl-certificate
        volumeMounts:
          - mountPath: /run/conjur
            name: conjur-access-token
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
        - name: summon-config
          configMap:
            name: cityapp-summon-init-config
#### This is not required if using openshift integrated registry
#      imagePullSecrets:
#       - name: dockerpullsecret
